buildscript {
    repositories {
        maven { url = "https://maven.fabricmc.net/" }
        mavenCentral()
    }
    dependencies {
        classpath "net.fabricmc:fabric-loom:1.17.21"
    }
}

apply plugin: "fabric-loom"
apply plugin: "maven-publish"

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:1.16.5"
    mappings "net.fabricmc:yarn:1.16.5+build.10:v2"
    modImplementation "net.fabricmc:fabric-loader:0.15.11"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.42.0+1.16"
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 8
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.name}" }
    }
}
