# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.16.5
loader_version=0.15.11
loom_version=1.17.21

# Mod Properties
version=1.0.0
group=com.example

# Dependencies
fabric_api_version=0.42.0+1.16
